### ISSUE TITLE
Codes

### ISSUE THREAD

**Issue by us** [muan/github-dashboard#15]
When I didn't choose code, it doesn't show anything.
![Screen Shot 2019-04-15 at 9 59 18 AM](https://user-images.githubusercontent.com/22618852/56113053-686fbe00-5f65-11e9-9ef2-8b017cc54d9b.png)

**Comment by muan** [comment]
I can't seem to reproduce this. The visibility are all controlled by these CSS classes: https://github.com/muan/github-dashboard/blob/master/dashboard.css

If you can provide your news feed markup I might be able to see what's happening.
