### ISSUE TITLE
Search Organization in Fork Window chrome extenstion request

### ISSUE THREAD

**Issue by shujaatak** [muan/github-dashboard#17]
It's time consuming and hard to scroll and look for the organization in the **Fork Window**, it would be awesome if there was a search box where one could enter the starting characters of the organization name and matching organization or orgnaizations automatically get filtered and shown in the window.

Can you make such an open source extension please?

Right now fork window is like this:
![Before](https://user-images.githubusercontent.com/14161646/64063588-699d4100-cc0f-11e9-86df-2b992e390e2a.png)

And one way of required fork window with organization search bar could be:
![After](https://user-images.githubusercontent.com/14161646/64063591-7883f380-cc0f-11e9-80f6-3da5677d6ebe.png)

**Comment by muan** [comment]
No
